export const FAKEBANK_LOCATIONS = [
  {
    id: 1,
    title: "FakeBank Antwerpen",
    description: "Filiaal Antwerpen",
    latitude: 51.2194,
    longitude: 4.4025,
  },
  {
    id: 2,
    title: "FakeBank Brussel",
    description: "Filiaal Brussel",
    latitude: 50.8503,
    longitude: 4.3517,
  },
  {
    id: 3,
    title: "FakeBank Gent",
    description: "Filiaal Gent",
    latitude: 51.0543,
    longitude: 3.7174,
  },
  {
    id: 4,
    title: "FakeBank Brugge",
    description: "Filiaal Brugge",
    latitude: 51.2093,
    longitude: 3.2247,
  },
  {
    id: 5,
    title: "FakeBank Leuven",
    description: "Filiaal Leuven",
    latitude: 50.8798,
    longitude: 4.7005,
  },
  {
    id: 6,
    title: "FakeBank Hasselt",
    description: "Filiaal Hasselt",
    latitude: 50.93,
    longitude: 5.332,
  },
  {
    id: 7,
    title: "FakeBank Mechelen",
    description: "Filiaal Mechelen",
    latitude: 51.0251,
    longitude: 4.4777,
  },
  {
    id: 8,
    title: "FakeBank Kortrijk",
    description: "Filiaal Kortrijk",
    latitude: 50.8078,
    longitude: 3.2667,
  },
  {
    id: 9,
    title: "FakeBank Mons",
    description: "Filiaal Mons",
    latitude: 50.454,
    longitude: 3.9519,
  },
  {
    id: 10,
    title: "FakeBank Liège",
    description: "Filiaal Liège",
    latitude: 50.6326,
    longitude: 5.5797,
  },
];
